version: 2.1

jobs:
  install_dependencies:
    docker:
      - image: cypress/browsers:node16.14.2-chrome89
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install

  run_tests:
    docker:
      - image: cypress/browsers:node16.14.2-chrome89
    steps:
      - checkout
      - run:
          name: Run tests
          command: npx cypress run

  generate_report:
    docker:
      - image: cypress/browsers:node16.14.2-chrome89
    steps:
      - checkout
      - run:
          name: Generate Allure report
          command: npm run report:allure

workflows:
  version: 2
  build_and_test:
    jobs:
      - install_dependencies
      - run_tests:
          requires:
            - install_dependencies
      - generate_report:
          requires:
            - run_tests
