version: 2.1

orbs:
  cypress: cypress-io/cypress@3.3.1

jobs:
  build:
    docker:
      - image: cypress/browsers:node16.14.2-slim-chrome103-ff102
    steps:
      - checkout
      - cypress/install
      - run:
          name: Install Cypress explicitly
          command: npm install cypress
      - run:
          name: Verify Cypress installation
          command: npx cypress verify
      - run:
          name: Run Cypress tests with custom command
          command: npm run cypress:run
      - run:
          name: Update packages and install Java
          command: |
            apt-get update
            apt-get install -y openjdk-11-jdk
            echo 'export JAVA_HOME="/usr/lib/jvm/java-11-openjdk-amd64"' >> $BASH_ENV
            echo 'export PATH="$JAVA_HOME/bin:$PATH"' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Generate Allure report
          command: npm run report:allure

workflows:
  build_and_test:
    jobs:
      - build
