version: 2.1

orbs:
  cypress: cypress-io/cypress@3.3.1

jobs:
  build:
    docker:
      - image: cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1
    steps:
      - checkout
      - cypress/install
      - run:
          name: Install Java
          command: |
            apt-get update
            apt-get install -y default-jdk
            echo 'export JAVA_HOME="$(dirname $(dirname $(readlink -f $(which javac))))"' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Install Cypress explicitly
          command: npm install cypress
      - run:
          name: Verify Cypress installation
          command: npx cypress verify
      - run:
          name: Run Cypress tests with custom command
          command: npm run cypress:run
      - run:
          name: Generate Allure report
          command: npm run report:allure

workflows:
  build_and_test:
    jobs:
      - build
