version: 2.1

jobs:
  install_dependencies:
    docker:
      - image: cypress/browsers:node16.14.2-slim-chrome103-ff102
    steps:
      - checkout
      - run:
          name: Install dependencies using npm ci
          command: npm ci
      - run:
          name: Install Cypress explicitly
          command: npm install cypress
      - run:
          name: Verify Cypress
          command: npx cypress verify

  run_tests:
    docker:
      - image: cypress/browsers:node16.14.2-slim-chrome103-ff102
    steps:
      - checkout
      - run:
          name: Run tests
          command: npm run cypress:run

  generate_report:
    docker:
      - image: cypress/browsers:node16.14.2-slim-chrome103-ff102
    steps:
      - checkout
      - run:
          name: Generate Allure report
          command: npm run report:allure

workflows:
  version: 2
  build_and_test:
    jobs:
      - install_dependencies
      - run_tests:
          requires:
            - install_dependencies
      - generate_report:
          requires:
            - run_tests
