version: 2.1

orbs:
  cypress: cypress-io/cypress@3.3.1

jobs:
  build:
    docker:
      - image: cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1
    steps:
      - checkout
      - cypress/install
      - run:
          name: Remove duplicate package sources
          command: |
            rm -f /etc/apt/sources.list.d/microsoft-edge-stable.list
            rm -f /etc/apt/sources.list.d/microsoft-edge.list
            apt-get update
      - run:
          name: Create missing directory for Java installation
          command: mkdir -p /usr/share/man/man1
      - run:
          name: Install Java
          command: |
            apt-get update && apt-get purge -y openjdk-11-jdk-headless openjdk-11-jre-headless ca-certificates-java && \
            apt-get install -y openjdk-11-jdk-headless ca-certificates-java
      - run:
          name: Install Cypress explicitly
          command: npm install cypress
      - run:
          name: Verify Cypress installation
          command: npx cypress verify
      - run:
          name: Run Cypress tests with custom command
          command: npm run cypress:run
      - run:
          name: Generate Allure report
          command: allure generate --clean
          when: always
      - store_artifacts:
          path: /home/circleci/project/allure-report

workflows:
  build_and_test:
    jobs:
      - build
