version: 2.1

jobs:
  install_dependencies:
    docker:
      - image: cimg/node:16.14.2 # Вы можете выбрать нужную вам версию Node
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install

  run_tests:
    docker:
      - image: cimg/node:14.17.0
    steps:
      - checkout
      - run:
          name: Run tests
          command: npm run run

  generate_report:
    docker:
      - image: cimg/node:14.17.0
    steps:
      - checkout
      - run:
          name: Generate Allure report
          command: npm run report:allure

workflows:
  version: 2
  build_and_test:
    jobs:
      - install_dependencies
      - run_tests:
          requires:
            - install_dependencies
      - generate_report:
          requires:
            - run_tests
